site :opscode

metadata

cookbook 'apt', '~>1.7.0'
cookbook 'build-essential'
cookbook 'git'

cookbook 'mariadb', github: 'MarcinKoziuk/chef-mariadb'
cookbook 'nginx'
cookbook 'redisio', github: 'brianbianco/redisio'