---
driver_plugin: vagrant

platforms:
- name: precise64
  driver_config:
    box: precise64
    box_url: http://dl.dropbox.com/u/1537815/precise64.box
    require_chef_omnibus: true

suites:
- name: default
  run_list: 
    - recipe[sec-base]
    - recipe[minitest-handler]
  attributes: {}
