# fly.toml app configuration file generated for jigsee on 2025-10-23T04:26:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jigsee'
primary_region = 'lax'

[build]
  image = "ghcr.io/tphummel/jigseer:latest"

[env]
  JIGSEER_DB_PATH = "/data/jigseer.sqlite"

[mounts]
  source = "jigsee"
  destination = "/data"
  processes = ["app"] # optional - attach volumes to Machines that belong to one or more process groups
  initial_size = "1gb" # optional - the size of the volume created on first deploy


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1024'
  cpu_kind = 'shared'
  cpus = 1
