# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.hostname = "app-base-lnmn"

  config.vm.box = "precise64"

  config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"

  config.vm.network :private_network, ip: "33.33.33.10"

  config.vm.provider :virtualbox do |vb|
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.ssh.max_tries = 40
  config.ssh.timeout   = 120

  config.omnibus.chef_version = '10.26.0'

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      :mysql => {
        :server_root_password => 'rootpass',
        :server_debian_password => 'debpass',
        :server_repl_password => 'replpass'
      }
    }

    chef.run_list = [
        "recipe[app-base-lnmn::default]"
    ]
    chef.data_bags_path = "./data_bags"
  end
end