name: jigseer

on:
  push:
    paths:
      - 'jigseer/**'
      - '.github/workflows/jigseer.yml'
  pull_request:
    paths:
      - 'jigseer/**'
      - '.github/workflows/jigseer.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: jigseer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test harness
        run: php tests/run.php
        working-directory: jigseer

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./jigseer
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
